[2024-09-15T16:49:19.715+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-15T16:49:19.755+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_product_bash.retailDataWithAirflow manual__2024-09-15T16:49:16.155395+00:00 [queued]>
[2024-09-15T16:49:19.773+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_product_bash.retailDataWithAirflow manual__2024-09-15T16:49:16.155395+00:00 [queued]>
[2024-09-15T16:49:19.774+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-15T16:49:19.801+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): retailDataWithAirflow> on 2024-09-15 16:49:16.155395+00:00
[2024-09-15T16:49:19.814+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=666) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-15T16:49:19.817+0000] {standard_task_runner.py:72} INFO - Started process 667 to run task
[2024-09-15T16:49:19.817+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_product_bash', 'retailDataWithAirflow', 'manual__2024-09-15T16:49:16.155395+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/retailData_dags.py', '--cfg-path', '/tmp/tmpqpcuesoz']
[2024-09-15T16:49:19.820+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask retailDataWithAirflow
[2024-09-15T16:49:19.918+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_product_bash.retailDataWithAirflow manual__2024-09-15T16:49:16.155395+00:00 [running]> on host 6b58833345bd
[2024-09-15T16:49:20.108+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='customer_product_bash' AIRFLOW_CTX_TASK_ID='retailDataWithAirflow' AIRFLOW_CTX_EXECUTION_DATE='2024-09-15T16:49:16.155395+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-15T16:49:16.155395+00:00'
[2024-09-15T16:49:20.111+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-15T16:49:20.148+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-15T16:49:20.150+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/script/retailDataWithAirflow.py']
[2024-09-15T16:49:20.174+0000] {subprocess.py:86} INFO - Output:
[2024-09-15T16:49:23.100+0000] {subprocess.py:93} INFO - /opt/***/dags/script/retailDataWithAirflow.py:116: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-09-15T16:49:23.102+0000] {subprocess.py:93} INFO -   df.to_sql(name=self.table_name, con=connection, index=False, if_exists='replace')
[2024-09-15T16:49:23.496+0000] {subprocess.py:93} INFO - /opt/***/dags/script/retailDataWithAirflow.py:116: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-09-15T16:49:23.498+0000] {subprocess.py:93} INFO -   df.to_sql(name=self.table_name, con=connection, index=False, if_exists='replace')
[2024-09-15T16:49:23.499+0000] {subprocess.py:93} INFO - Error loading data to database: 'Connection' object has no attribute 'cursor'
[2024-09-15T16:49:23.499+0000] {subprocess.py:93} INFO - Error loading data to database: 'Connection' object has no attribute 'cursor'
[2024-09-15T16:49:23.672+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-15T16:49:23.730+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-15T16:49:23.733+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_product_bash, task_id=retailDataWithAirflow, run_id=manual__2024-09-15T16:49:16.155395+00:00, execution_date=20240915T164916, start_date=20240915T164919, end_date=20240915T164923
[2024-09-15T16:49:23.784+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-15T16:49:23.835+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-15T16:49:23.839+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
