[2024-09-16T14:48:29.374+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-16T14:48:29.414+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_alchemy.create_table_alchemy manual__2024-09-16T14:48:25.880015+00:00 [queued]>
[2024-09-16T14:48:29.443+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_alchemy.create_table_alchemy manual__2024-09-16T14:48:25.880015+00:00 [queued]>
[2024-09-16T14:48:29.444+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-16T14:48:29.481+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): create_table_alchemy> on 2024-09-16 14:48:25.880015+00:00
[2024-09-16T14:48:29.492+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=455) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-16T14:48:29.495+0000] {standard_task_runner.py:72} INFO - Started process 456 to run task
[2024-09-16T14:48:29.495+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_alchemy', 'create_table_alchemy', 'manual__2024-09-16T14:48:25.880015+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/test_alchemy_dags.py', '--cfg-path', '/tmp/tmp5zpst3mr']
[2024-09-16T14:48:29.498+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask create_table_alchemy
[2024-09-16T14:48:29.589+0000] {task_command.py:467} INFO - Running <TaskInstance: test_alchemy.create_table_alchemy manual__2024-09-16T14:48:25.880015+00:00 [running]> on host e54c4d73c780
[2024-09-16T14:48:29.778+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='test_alchemy' AIRFLOW_CTX_TASK_ID='create_table_alchemy' AIRFLOW_CTX_EXECUTION_DATE='2024-09-16T14:48:25.880015+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-16T14:48:25.880015+00:00'
[2024-09-16T14:48:29.780+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-16T14:48:29.811+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-16T14:48:29.813+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/script/test_alchemy.py']
[2024-09-16T14:48:29.836+0000] {subprocess.py:86} INFO - Output:
[2024-09-16T14:48:32.679+0000] {subprocess.py:93} INFO - /opt/***/dags/script/test_alchemy.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-09-16T14:48:32.681+0000] {subprocess.py:93} INFO -   df.to_sql(name=self.table_name, con=conn, index=False, if_exists='replace')
[2024-09-16T14:48:32.682+0000] {subprocess.py:93} INFO - Error loading data to database: 'Connection' object has no attribute 'cursor'
[2024-09-16T14:48:32.867+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-16T14:48:32.922+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-16T14:48:32.924+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_alchemy, task_id=create_table_alchemy, run_id=manual__2024-09-16T14:48:25.880015+00:00, execution_date=20240916T144825, start_date=20240916T144829, end_date=20240916T144832
[2024-09-16T14:48:32.973+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-16T14:48:33.019+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-16T14:48:33.024+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
