[2024-09-12T18:34:23.690+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-12T18:34:23.733+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_airflow.say_welcome_test manual__2024-09-12T18:34:21.525914+00:00 [queued]>
[2024-09-12T18:34:23.755+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_airflow.say_welcome_test manual__2024-09-12T18:34:21.525914+00:00 [queued]>
[2024-09-12T18:34:23.756+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-12T18:34:23.790+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): say_welcome_test> on 2024-09-12 18:34:21.525914+00:00
[2024-09-12T18:34:23.801+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=246) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-12T18:34:23.804+0000] {standard_task_runner.py:72} INFO - Started process 247 to run task
[2024-09-12T18:34:23.805+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_***', 'say_welcome_test', 'manual__2024-09-12T18:34:21.525914+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/test_dags.py', '--cfg-path', '/tmp/tmpv93blm2s']
[2024-09-12T18:34:23.808+0000] {standard_task_runner.py:105} INFO - Job 42: Subtask say_welcome_test
[2024-09-12T18:34:23.900+0000] {task_command.py:467} INFO - Running <TaskInstance: test_airflow.say_welcome_test manual__2024-09-12T18:34:21.525914+00:00 [running]> on host 9c5d837b6f3b
[2024-09-12T18:34:24.082+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='test_***' AIRFLOW_CTX_TASK_ID='say_welcome_test' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T18:34:21.525914+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-12T18:34:21.525914+00:00'
[2024-09-12T18:34:24.084+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-12T18:34:24.119+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-12T18:34:24.121+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Hallo !"']
[2024-09-12T18:34:24.143+0000] {subprocess.py:86} INFO - Output:
[2024-09-12T18:34:24.146+0000] {subprocess.py:93} INFO - Hallo !
[2024-09-12T18:34:24.150+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-12T18:34:24.200+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-12T18:34:24.202+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_***, task_id=say_welcome_test, run_id=manual__2024-09-12T18:34:21.525914+00:00, execution_date=20240912T183421, start_date=20240912T183423, end_date=20240912T183424
[2024-09-12T18:34:24.264+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-12T18:34:24.315+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-12T18:34:24.320+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
