[2024-09-13T09:49:23.955+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-13T09:49:23.990+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_product_bash.retailDataWithAirflow manual__2024-09-13T09:49:20.047263+00:00 [queued]>
[2024-09-13T09:49:24.007+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_product_bash.retailDataWithAirflow manual__2024-09-13T09:49:20.047263+00:00 [queued]>
[2024-09-13T09:49:24.008+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-13T09:49:24.037+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): retailDataWithAirflow> on 2024-09-13 09:49:20.047263+00:00
[2024-09-13T09:49:24.048+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3950) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-13T09:49:24.050+0000] {standard_task_runner.py:72} INFO - Started process 3951 to run task
[2024-09-13T09:49:24.051+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_product_bash', 'retailDataWithAirflow', 'manual__2024-09-13T09:49:20.047263+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/retailData_dags.py', '--cfg-path', '/tmp/tmpjbbwe9fu']
[2024-09-13T09:49:24.056+0000] {standard_task_runner.py:105} INFO - Job 87: Subtask retailDataWithAirflow
[2024-09-13T09:49:24.140+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_product_bash.retailDataWithAirflow manual__2024-09-13T09:49:20.047263+00:00 [running]> on host 9c5d837b6f3b
[2024-09-13T09:49:24.315+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='customer_product_bash' AIRFLOW_CTX_TASK_ID='retailDataWithAirflow' AIRFLOW_CTX_EXECUTION_DATE='2024-09-13T09:49:20.047263+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-13T09:49:20.047263+00:00'
[2024-09-13T09:49:24.317+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-13T09:49:24.345+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-13T09:49:24.347+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/script/retailDataWithAirflow.py']
[2024-09-13T09:49:24.366+0000] {subprocess.py:86} INFO - Output:
[2024-09-13T09:49:27.311+0000] {subprocess.py:93} INFO - /opt/***/dags/script/retailDataWithAirflow.py:115: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-09-13T09:49:27.313+0000] {subprocess.py:93} INFO -   df.to_sql(name=self.table_name, con=connection, index=False, if_exists='replace')
[2024-09-13T09:49:27.734+0000] {subprocess.py:93} INFO - /opt/***/dags/script/retailDataWithAirflow.py:115: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-09-13T09:49:27.736+0000] {subprocess.py:93} INFO -   df.to_sql(name=self.table_name, con=connection, index=False, if_exists='replace')
[2024-09-13T09:49:27.737+0000] {subprocess.py:93} INFO - Error loading data to database: 'Connection' object has no attribute 'cursor'
[2024-09-13T09:49:27.738+0000] {subprocess.py:93} INFO - Error loading data to database: 'Connection' object has no attribute 'cursor'
[2024-09-13T09:49:27.948+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-13T09:49:28.005+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-13T09:49:28.006+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_product_bash, task_id=retailDataWithAirflow, run_id=manual__2024-09-13T09:49:20.047263+00:00, execution_date=20240913T094920, start_date=20240913T094923, end_date=20240913T094928
[2024-09-13T09:49:28.093+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-13T09:49:28.138+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-13T09:49:28.142+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
