[2024-09-14T16:43:02.103+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-14T16:43:02.135+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_pgadmin.say_end_pgadmin manual__2024-09-14T16:42:48.085914+00:00 [queued]>
[2024-09-14T16:43:02.156+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_pgadmin.say_end_pgadmin manual__2024-09-14T16:42:48.085914+00:00 [queued]>
[2024-09-14T16:43:02.157+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-14T16:43:02.187+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): say_end_pgadmin> on 2024-09-14 16:42:48.085914+00:00
[2024-09-14T16:43:02.198+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=906) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-14T16:43:02.200+0000] {standard_task_runner.py:72} INFO - Started process 907 to run task
[2024-09-14T16:43:02.200+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_pgadmin', 'say_end_pgadmin', 'manual__2024-09-14T16:42:48.085914+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/test_pgadmin_dags.py', '--cfg-path', '/tmp/tmpfk4r95l9']
[2024-09-14T16:43:02.203+0000] {standard_task_runner.py:105} INFO - Job 145: Subtask say_end_pgadmin
[2024-09-14T16:43:02.284+0000] {task_command.py:467} INFO - Running <TaskInstance: test_pgadmin.say_end_pgadmin manual__2024-09-14T16:42:48.085914+00:00 [running]> on host 0a5b2fe35fbd
[2024-09-14T16:43:02.451+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='test_pgadmin' AIRFLOW_CTX_TASK_ID='say_end_pgadmin' AIRFLOW_CTX_EXECUTION_DATE='2024-09-14T16:42:48.085914+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-14T16:42:48.085914+00:00'
[2024-09-14T16:43:02.453+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-14T16:43:02.482+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-14T16:43:02.484+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Good Bye ..."']
[2024-09-14T16:43:02.506+0000] {subprocess.py:86} INFO - Output:
[2024-09-14T16:43:02.509+0000] {subprocess.py:93} INFO - Good Bye ...
[2024-09-14T16:43:02.511+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-14T16:43:02.557+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-14T16:43:02.558+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_pgadmin, task_id=say_end_pgadmin, run_id=manual__2024-09-14T16:42:48.085914+00:00, execution_date=20240914T164248, start_date=20240914T164302, end_date=20240914T164302
[2024-09-14T16:43:02.620+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-14T16:43:02.659+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-14T16:43:02.663+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
